### ISSUE TITLE
RuntimeError: 

### ISSUE THREAD

**Issue by levchCode** [QISKit/qiskit-sdk-py#247]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 102, in <module>
    decrypt((7, 51), "4QG4")
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 66, in decrypt
    m_list = findPQ(2, public_key[1])
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 47, in findPQ
    result = qp.execute(['Shor'])#, backend='ibmqx5', shots=1024, wait=5, timeout=1200)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1413, in execute
    result = self.run(qobj, wait=wait, timeout=timeout)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1232, in run
    timeout=timeout)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1315, in _run_internal
    job_processor.submit()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_jobprocessor.py", line 118, in submit
    future = executor.submit(run_backend, q_job)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 466, in submit
    self._start_queue_management_thread()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 427, in _start_queue_management_thread
    self._adjust_process_count()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 446, in _adjust_process_count
    p.start()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 102, in <module>
    decrypt((7, 51), "4QG4")
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 66, in decrypt
    m_list = findPQ(2, public_key[1])
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 47, in findPQ
    result = qp.execute(['Shor'])#, backend='ibmqx5', shots=1024, wait=5, timeout=1200)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1413, in execute
    result = self.run(qobj, wait=wait, timeout=timeout)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1232, in run
    timeout=timeout)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1315, in _run_internal
    job_processor.submit()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_jobprocessor.py", line 118, in submit
    future = executor.submit(run_backend, q_job)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 466, in submit
    self._start_queue_management_thread()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 427, in _start_queue_management_thread
    self._adjust_process_count()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 446, in _adjust_process_count
    p.start()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 102, in <module>
    decrypt((7, 51), "4QG4")
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 66, in decrypt
    m_list = findPQ(2, public_key[1])
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 47, in findPQ
    result = qp.execute(['Shor'])#, backend='ibmqx5', shots=1024, wait=5, timeout=1200)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1413, in execute
    result = self.run(qobj, wait=wait, timeout=timeout)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1232, in run
    timeout=timeout)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1315, in _run_internal
    job_processor.submit()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_jobprocessor.py", line 118, in submit
    future = executor.submit(run_backend, q_job)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 466, in submit
    self._start_queue_management_thread()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 427, in _start_queue_management_thread
    self._adjust_process_count()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 446, in _adjust_process_count
    p.start()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 102, in <module>
    decrypt((7, 51), "4QG4")
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 66, in decrypt
    m_list = findPQ(2, public_key[1])
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 47, in findPQ
    result = qp.execute(['Shor'])#, backend='ibmqx5', shots=1024, wait=5, timeout=1200)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1413, in execute
    result = self.run(qobj, wait=wait, timeout=timeout)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1232, in run
    timeout=timeout)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1315, in _run_internal
    job_processor.submit()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_jobprocessor.py", line 118, in submit
    future = executor.submit(run_backend, q_job)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 466, in submit
    self._start_queue_management_thread()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 427, in _start_queue_management_thread
    self._adjust_process_count()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 446, in _adjust_process_count
    p.start()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 102, in <module>
    decrypt((7, 51), "4QG4")
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 66, in decrypt
    m_list = findPQ(2, public_key[1])
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 47, in findPQ
    result = qp.execute(['Shor'])#, backend='ibmqx5', shots=1024, wait=5, timeout=1200)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1413, in execute
    result = self.run(qobj, wait=wait, timeout=timeout)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1232, in run
    timeout=timeout)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_quantumprogram.py", line 1315, in _run_internal
    job_processor.submit()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_jobprocessor.py", line 118, in submit
    future = executor.submit(run_backend, q_job)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 466, in submit
    self._start_queue_management_thread()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 427, in _start_queue_management_thread
    self._adjust_process_count()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 446, in _adjust_process_count
    p.start()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 102, in <module>
    decrypt((7, 51), "4QG4")
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 66, in decrypt
    m_list = findPQ(2, public_key[1])
  File "C:\Users\levchy\Desktop\Shor\RSA_breaker.py", line 48, in findPQ
    res = result.get_counts('Shor')
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_result.py", line 233, in get_counts
    return self.get_data(name)['counts']
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_result.py", line 204, in get_data
    raise exception
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\_jobprocessor.py", line 99, in _job_done_callback
    result = future.result()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\levchy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

This error popped up when I tried
result = qp.execute(['Bell'])
res = result.get_counts('Bell')

Turns out it happens when I use a local simulator. So I switched to this line. Works for now:
result = qp.execute(['Shor'], backend='ibmqx_qasm_simulator', shots=1024, wait=5, timeout=1200)

##  Environment
* Version used: qiskit 0.4.4
* Environment name and version (e.g. Python 3.6.1): Python 3.6.4
* Operating System and version: Windows 10

**Comment by atilag** [comment]
Can I see the entire program?
Thanks!

**Comment by atilag** [comment]
Actually, there's no need to show me the code.
You need to add the python main entry to your program, something like:
```python

# Here are my imports
(...)
import qiskit

# Maybe some function definitions here
(...)

if __name__ == '__main__':  # <--- this is what your program needs
    # My program starts here!!
```
Let me know it that works for you :)

**Comment by levchCode** [comment]
Oh, I see now. Thank you!

**Comment by nonhermitian** [comment]
Note that the multiprocessing library must create a new python interpreter for each thread created in Windows, and thus is quite slow.  In fact, in many cases it can be slower than serial execution.  One might want to have a flag for serial execution to handle cases on Windows.

**Comment by atilag** [comment]
@nonhermitian yeah, for short circuits serial execution seems the way to go. We need to make some performance tests though to see where the threshold would be. Can you create an issue with the  `enhancement` tag?. Thanks!
