### ISSUE TITLE
"make profile" fails because of a parsing error in test_qasm_python_simulator.py

### ISSUE THREAD

**Issue by atilag** [QISKit/qiskit-sdk-py#27]
Running make profile outputs:
```
======================================================================
ERROR: profile_nqubit_speed_constant_depth (test.python.test_qasm_python_simulator.LocalQasmSimulatorTest)
simulation time vs the number of qubits
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jgomez/ibm/quantum/qiskit-sdk-py/test/python/test_qasm_python_simulator.py", line 342, in profile_nqubit_speed_constant_depth
    qp.run()
TypeError: run() missing 1 required positional argument: 'qobj'

======================================================================
ERROR: profile_nqubit_speed_grow_depth (test.python.test_qasm_python_simulator.LocalQasmSimulatorTest)
simulation time vs the number of qubits
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jgomez/ibm/quantum/qiskit-sdk-py/test/python/test_qasm_python_simulator.py", line 267, in profile_nqubit_speed_grow_depth
    qp.run()
TypeError: run() missing 1 required positional argument: 'qobj'

----------------------------------------------------------------------
```

## Steps to Reproduce (for bugs)

1. run: make profile
2.
3.
4.

## Your Environment

* Version used: master (r0.3)
* Environment name and version (e.g. Python 3.6.1): Python3.5/3.6
* Operating System and version: Linux (but Mac and Windows are affected as well)

**Comment by atilag** [comment]
Seems like Erick already fixed this bug in Dev branch. So I cherry-picked the specific commit and pushed it to r0.3 and master branches.
