### ISSUE TITLE
two-qubit-kak error when computing phase

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-sdk-py#445]
When I run the following program, I encountered an error:
```
#setup
from qiskit import QuantumProgram
import Qconfig

qp = QuantumProgram()
qp.set_api(Qconfig.APItoken, Qconfig.config['url'])

from qiskit.mapper import two_qubit_kak


import numpy as np

perm = np.array([[0.,0.,0.,1.], [1.,0.,0.,0.], [0.,1.,0.,0.], [0.,0.,1.,0.] ])

permCircuit = two_qubit_kak(perm)

print(perm)

print(permCircuit)
```

## Expected Behavior

It should produce a circuit for the unitary matrix below: 
```
[ 
 [0,0,0,1],
 [1,0,0,0],
 [0,1,0,0],
 [0,0,1,0]
]
```

## Current Behavior

It gives an error message:
```
/Users/rraymondhp/miniconda3/envs/QISKitenv/lib/python3.6/site-packages/qiskit/mapper/_compiling.py:162: RuntimeWarning: invalid value encountered in double_scalars
  phase = np.linalg.det(unitary_matrix)**(-1.0/4.0)
Traceback (most recent call last):
  File "test_u.py", line 15, in <module>
    permCircuit = two_qubit_kak(perm)
  File "/Users/rraymondhp/miniconda3/envs/QISKitenv/lib/python3.6/site-packages/qiskit/mapper/_compiling.py", line 177, in two_qubit_kak
    D, P = np.linalg.eig(M2)
  File "/Users/rraymondhp/miniconda3/envs/QISKitenv/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 1143, in eig
    _assertFinite(a)
  File "/Users/rraymondhp/miniconda3/envs/QISKitenv/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 216, in _assertFinite
    raise LinAlgError("Array must not contain infs or NaNs")
numpy.linalg.linalg.LinAlgError: Array must not contain infs or NaNs

```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by awcross1** [comment]
Ok, thanks @nonhermitian , I guess the problem is different. However, I have run into other issues with this method for the reasons above. The eigenvectors returned from eig are not orthogonal in some cases.

**Comment by nonhermitian** [comment]
@awcross1 that is possible if the input matrix is non-Hermitian (non-symmetric in real case), even if the spectrum is non-degenerate.
